name: Hello World
on: workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: build phase
        run: echo "Build Phase done"
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test phase
        run: echo "Test Phase Done"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Phase
        run: echo "Deploy Phase Done"
        
        
                  
        
  
