name: Output Demo
on: push
jobs:
  build:
    outputs:
      version: ${{steps.step1.outputs.version}}
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        id: step1
        run: echo "version=0.0.2" >> $GITHUB_OUTPUT

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Steps
        run: echo "The Version of the Build job is ${{needs.build.outputs.version}}"
    
